const contractAddress = "0x26fDC7Ab491dcf874BB06F33b49f02dd59721cc3"; // Replace with your own contract address
const chain = 'polygon'; // rinkeby, polygon, or ethereum

const welcome_h1 = "Welcome to the Big Cats Universe NFT Project!!";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'The Big Cats Universe NFT Project apart from arts, virtual commerce and other earnings,also supports helping stray animals. ';
const h1_presale_coming_soon = "NFT Drop Coming Soon!!";
const h1_presale_mint = "Pre-Sale Minting Open!!";
const h1_public_mint = "Public Minting Open!!";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale.. ";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 🐯";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🐯";
const p_public_mint = "No whitelist needed. Public minting is now open! 🦁";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your Special NFT";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The Community";
const button_public_mint = "Mint Your NFT";
const mint_failed = "Minting failed. 😿 Please try again.";
